//! Golden wire vectors, produced by two independent implementations of the
//! same protocol rather than by this port.
//!
//! * `reference/reference_vectors.txt` — the third-party Python client the
//!   default profile follows, regenerated by `reference/gen_vectors.py`.
//! * `reference/official_vectors.txt` — the Java/Android generation written
//!   against captured official-client traffic, regenerated by
//!   `reference/gen_official_vectors.py`.
//!
//! The tests compare the Rust builders against those bytes instead of against
//! hand-written expectations, so a layout drift cannot hide behind a matching
//! assertion.

const REFERENCE_FILE: &str = include_str!("../reference/reference_vectors.txt");
const OFFICIAL_FILE: &str = include_str!("../reference/official_vectors.txt");

/// Looks up a named vector from the Python-client profile.
pub(crate) fn vector(name: &str) -> Vec<u8> {
    lookup(REFERENCE_FILE, name).unwrap_or_else(|| {
        panic!("reference vector `{name}` is missing from reference_vectors.txt")
    })
}

/// Looks up a named vector from the Java/Android profile.
pub(crate) fn official_vector(name: &str) -> Vec<u8> {
    lookup(OFFICIAL_FILE, name)
        .unwrap_or_else(|| panic!("official vector `{name}` is missing from official_vectors.txt"))
}

fn lookup(file: &str, name: &str) -> Option<Vec<u8>> {
    file.lines().find_map(|line| {
        let (key, value) = line.split_once(" = ")?;
        (key.trim() == name).then(|| decode_hex(value.trim()))
    })
}

fn decode_hex(text: &str) -> Vec<u8> {
    assert!(
        text.len().is_multiple_of(2),
        "reference vector hex must have an even length"
    );
    text.as_bytes()
        .as_chunks::<2>()
        .0
        .iter()
        .map(|pair| {
            let digit = |byte: u8| match byte {
                b'0'..=b'9' => byte - b'0',
                b'a'..=b'f' => byte - b'a' + 10,
                b'A'..=b'F' => byte - b'A' + 10,
                other => panic!("invalid hex digit {}", other as char),
            };
            (digit(pair[0]) << 4) | digit(pair[1])
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn vectors_are_present_and_well_formed() {
        assert_eq!(vector("keepalive.type1.first").len(), 40);
        assert!(vector("login.user8.pwd8").len() > 300);
        assert_eq!(official_vector("official.keep40.data3").len(), 40);
        assert_eq!(official_vector("official.logout.user8.pwd8").len(), 80);
    }

    #[test]
    fn the_two_profiles_really_do_differ() {
        // The whole reason both vector files exist: the login frames are not the
        // same length, so a port cannot be validated against only one of them.
        assert_eq!(vector("login.user8.pwd8").len(), 368);
        assert_eq!(official_vector("official.login.user8.pwd8").len(), 338);
        assert_eq!(vector("login.user8.pwd16").len(), 374);
        assert_eq!(official_vector("official.login.user8.pwd16").len(), 346);
        // The keep-alive nonce is the other visible split: the Python client
        // hard-codes it, the Java rewrite randomises it.
        assert_eq!(&vector("keepalive.type1.next")[8..10], &[0x2f, 0x12]);
        assert_eq!(
            &official_vector("official.keep40.data1")[8..10],
            &[0x33, 0x44]
        );
    }
}
