//! UDP transport for the original Dr.COM authentication path.
//! Binding is explicit and causes no firewall, adapter, service, or driver changes.

use std::io;
use std::net::{Ipv4Addr, SocketAddr, SocketAddrV4, UdpSocket};
use std::time::Duration;

use socket2::{Domain, Protocol, Socket, Type};

/// Original default local authentication port, observed at `0x1003a900` and
/// in the original firewall rules. `BindRandomAddr` is a separate original
/// option and is deliberately selected by the caller rather than guessed.
pub const DEFAULT_LOCAL_PORT: u16 = 61440;

/// Windows reports a latched ICMP port-unreachable, generated by an *earlier*
/// datagram on the same socket, as `ConnectionReset` (or `ConnectionRefused`) on
/// this one. Neither kind means the current operation failed, so callers treat
/// them as transient instead of fatal.
pub fn is_transient_icmp(error: &io::Error) -> bool {
    matches!(
        error.kind(),
        io::ErrorKind::ConnectionReset | io::ErrorKind::ConnectionRefused
    )
}

pub struct UdpTransport {
    socket: UdpSocket,
}

impl UdpTransport {
    /// Binds the authentication socket.
    ///
    /// `SO_REUSEADDR` is set before binding, matching the reference clients: the
    /// original `DrAuthSvr.dll` path and the C# port both bind the fixed local
    /// port `61440` with `SocketOptionName.ReuseAddress`. Without it a bind
    /// fails outright while any other Dr.COM component still holds the port,
    /// which is the common case when the original client is running.
    pub fn bind(local_ip: Ipv4Addr, local_port: u16) -> io::Result<Self> {
        let socket = Socket::new(Domain::IPV4, Type::DGRAM, Some(Protocol::UDP))?;
        socket.set_reuse_address(true)?;
        socket.bind(&SocketAddrV4::new(local_ip, local_port).into())?;
        Ok(Self {
            socket: socket.into(),
        })
    }

    pub fn local_addr(&self) -> io::Result<SocketAddr> {
        self.socket.local_addr()
    }

    pub fn set_read_timeout(&self, timeout: Option<Duration>) -> io::Result<()> {
        self.socket.set_read_timeout(timeout)
    }

    /// Sends one datagram, retrying the transient ICMP errors described by
    /// [`is_transient_icmp`]. Without the retry the first send after such an
    /// error is dropped and the caller sees a spurious failure.
    pub fn send(&self, server: SocketAddrV4, datagram: &[u8]) -> io::Result<()> {
        let mut attempts = 0;
        loop {
            match self.send_once(server, datagram) {
                Err(error) if is_transient_icmp(&error) && attempts < 2 => {
                    attempts += 1;
                    std::thread::sleep(Duration::from_millis(20));
                }
                other => return other,
            }
        }
    }

    fn send_once(&self, server: SocketAddrV4, datagram: &[u8]) -> io::Result<()> {
        let count = self.socket.send_to(datagram, server)?;
        if count == datagram.len() {
            Ok(())
        } else {
            Err(io::Error::new(
                io::ErrorKind::WriteZero,
                "partial UDP datagram send",
            ))
        }
    }

    /// Returns the actual source address so the authentication layer can
    /// apply the original per-state server address checks.
    pub fn receive(&self, buffer: &mut [u8]) -> io::Result<(usize, SocketAddr)> {
        self.socket.recv_from(buffer)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn loopback_round_trip_keeps_source_and_packet_boundary() {
        let a = UdpTransport::bind(Ipv4Addr::LOCALHOST, 0).unwrap();
        let b = UdpTransport::bind(Ipv4Addr::LOCALHOST, 0).unwrap();
        b.set_read_timeout(Some(Duration::from_secs(1))).unwrap();
        let destination = match b.local_addr().unwrap() {
            SocketAddr::V4(addr) => addr,
            _ => unreachable!(),
        };
        a.send(destination, &[1, 2, 3, 4]).unwrap();
        let mut buffer = [0u8; 16];
        let (len, source) = b.receive(&mut buffer).unwrap();
        assert_eq!(&buffer[..len], &[1, 2, 3, 4]);
        assert_eq!(source, a.local_addr().unwrap());
    }
}
